# We are using travis to test the validity of the RDF and to deploy the files
# so we don't need a ruby or other language specific image
language: minimal

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - docker pull stain/jena
        - docker run -it --rm -v `pwd`:/rdf stain/jena riot -v --debug --validate --time examples/*\.{ttl,rdf}
